# AI Story Writer Configuration

[story]
# Default story settings
genre = "literary"
length = "short"
words = 1000
theme = ""
setting = ""

[generation]
# Generation method: auto, direct, outline
method = "auto"
validation_level = "standard"

[output]
# Output format and files
verbose = false
format = "pdf"  # text, json, pdf
output_file = ""
pdf_file = "story.pdf"

[advanced]
# Advanced settings (rarely changed)
model = "openai:gpt-4o"
temperature = 0.9
max_retries = 3
